export const IMAGE_POOL = [
  "https://images.pexels.com/photos/29440437/pexels-photo-29440437.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/31210634/pexels-photo-31210634.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/36745051/pexels-photo-36745051.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/5302663/pexels-photo-5302663.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/38128369/pexels-photo-38128369.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/12745603/pexels-photo-12745603.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/31196818/pexels-photo-31196818.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/37125137/pexels-photo-37125137.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/12745602/pexels-photo-12745602.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/31210664/pexels-photo-31210664.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
];

export type SeedCategory = {
  name: string;
  nameTa: string;
  slug: string;
  tagline: string;
  description: string;
  accent: string;
  icon: string;
  imageUrl: string;
};

export const SEED_CATEGORIES: SeedCategory[] = [
  {
    name: "One Sound Crackers",
    nameTa: "ஒற்றை வெடி",
    slug: "single-sound",
    tagline: "Classic Sivakasi Lakshmi & Kuruvi single sound crackers",
    description: "Traditional single report crackers with sharp decibel report and reliable fuses.",
    accent: "#FF3131",
    icon: "volume",
    imageUrl: "/categories/single-sound.jpg",
  },
  {
    name: "Flower Pots",
    nameTa: "பூச்சட்டி",
    slug: "flower-pots",
    tagline: "Golden fountains and color koti pots for the courtyard",
    description: "Classic high-rise golden and silver fountains with low smoke composition.",
    accent: "#D4AF37",
    icon: "sparkles",
    imageUrl: "/categories/flower-pots.jpg",
  },
  {
    name: "Premium Fountains",
    nameTa: "வண்ண ஃபவுண்டன்",
    slug: "fountains",
    tagline: "Multicolour crackling cones, showers and multi-step fountains",
    description: "Vibrant shower cones, multi-step fountains and tri-color pyro fountain displays.",
    accent: "#FF8C00",
    icon: "flame",
    imageUrl: "/categories/fountains.jpg",
  },
  {
    name: "Chakkars & Spinners",
    nameTa: "நிலச்சக்கரம்",
    slug: "ground-chakkar",
    tagline: "Speed wheels, wire chakkars and planet spinners",
    description: "High-rpm ground wheels and color changing spinners for kids and families.",
    accent: "#00D26A",
    icon: "disc",
    imageUrl: "/categories/ground-chakkar.jpg",
  },
  {
    name: "Bijili Crackers",
    nameTa: "பிஜிலி வெடி",
    slug: "bijili-crackers",
    tagline: "Red and super stripped bijili bags",
    description: "Crisp crackling bijilis packed in 50 and 100 piece bags.",
    accent: "#FF3131",
    icon: "zap",
    imageUrl: "/categories/bijili-crackers.jpg",
  },
  {
    name: "Wala Crackers",
    nameTa: "சரவெடி",
    slug: "wala-crackers",
    tagline: "Digital wala and 1000 wala continuous garlands",
    description: "Continuous garland crackers for grand celebrations and festival inaugurations.",
    accent: "#FF8C00",
    icon: "layers",
    imageUrl: "/categories/wala-crackers.jpg",
  },
  {
    name: "Bomb Novelties",
    nameTa: "பாம் வகைகள்",
    slug: "bombs",
    tagline: "Hydro, King of Kings and Digital sound bombs",
    description: "High-decibel sound bombs with heavy casing and water-resistant fuse.",
    accent: "#FF3131",
    icon: "bomb",
    imageUrl: "/categories/bombs.jpg",
  },
  {
    name: "Paper Flash Blast",
    nameTa: "பேப்பர் பிளாஸ்ட்",
    slug: "paper-flash",
    tagline: "Money Heist and Money in Bank paper flash novelties",
    description: "Colourful paper streamer explosions perfect for celebrations.",
    accent: "#0057FF",
    icon: "sparkles",
    imageUrl: "/categories/paper-flash.jpg",
  },
  {
    name: "Rockets",
    nameTa: "ராக்கெட்",
    slug: "rockets",
    tagline: "Whistling ascent, musical and bomb rockets",
    description: "High-flying rockets with whistling sound and bright canopy bursts.",
    accent: "#FF8C00",
    icon: "rocket",
    imageUrl: "/categories/rockets.jpg",
  },
  {
    name: "Twinkling Star",
    nameTa: "ட்விங்க்ளிங் ஸ்டார்",
    slug: "twinkling-star",
    tagline: "1½ inch & 4 inch star ropes and twinkling lights",
    description: "Continuous twinkling stars and pink rope crackers.",
    accent: "#F5D982",
    icon: "star",
    imageUrl: "/categories/twinkling-star.jpg",
  },
  {
    name: "Classic Candles",
    nameTa: "கேன்டில்ஸ்",
    slug: "candles",
    tagline: "Navrang, Ultra Colour and Magic light pencils",
    description: "Multi-color fountain pencils and crackling torches.",
    accent: "#00D26A",
    icon: "flame",
    imageUrl: "/categories/candles.jpg",
  },
  {
    name: "Hand Lighters",
    nameTa: "ஹேண்ட் லைட்டர்ஸ்",
    slug: "lighters",
    tagline: "Selfie sticks, 5G flash sticks and magic wands",
    description: "Long hand-held lighters with multi-color stars and crackling tips.",
    accent: "#D4AF37",
    icon: "wand",
    imageUrl: "/categories/lighters.jpg",
  },
  {
    name: "Peacock Fountain",
    nameTa: "மயில் ஃபவுண்டன்",
    slug: "peacock-fountain",
    tagline: "3 Wing, Peacock Tails and Bada Peacock fountains",
    description: "Majestic fan-shaped peacock fountain sprays in vibrant hues.",
    accent: "#0057FF",
    icon: "feather",
    imageUrl: "/categories/peacock-fountain.jpg",
  },
  {
    name: "Special Novelties",
    nameTa: "ஃபேன்சி வகைக‌ள்",
    slug: "novelties",
    tagline: "Vanitha, Ayyan and Ajanta brand premium novelties",
    description: "Brand novelty pyrotechnics, caterpillar, shot fountains and special effects.",
    accent: "#FF3131",
    icon: "gift",
    imageUrl: "/categories/novelties.jpg",
  },
  {
    name: "Sky Display & Multi Shots",
    nameTa: "வான வெடி",
    slug: "sky-shots",
    tagline: "Single sky displays, 12 to 240 multi-shots and mega set-outs",
    description: "Aerial shells, multi-color sky repeaters and 5x10 / 10x10 celebration set outs.",
    accent: "#0057FF",
    icon: "rocket",
    imageUrl: "/categories/sky-shots.jpg",
  },
  {
    name: "Premium Sparklers",
    nameTa: "மத்தாப்பு",
    slug: "sparklers",
    tagline: "10cm to 50cm Electric, Crackling, Red & Green sparklers",
    description: "Child-safe sparklers with bright light and low smoke emission.",
    accent: "#F5D982",
    icon: "wand",
    imageUrl: "/categories/sparklers.jpg",
  },
  {
    name: "Match Boxes",
    nameTa: "தீப்பெட்டி",
    slug: "match-boxes",
    tagline: "Classic 5 in 1 & 10 in 1 match boxes",
    description: "Safety matches for easy lighting.",
    accent: "#FF8C00",
    icon: "box",
    imageUrl: "/categories/match-boxes.jpg",
  },
  {
    name: "Hunters Gun",
    nameTa: "ரிங் கேப் கன்",
    slug: "hunters-gun",
    tagline: "MIB & Pirates ring cap guns for kids",
    description: "Toy ring cap guns with realistic sound effect.",
    accent: "#FF3131",
    icon: "target",
    imageUrl: "/categories/hunters-gun.jpg",
  },
  {
    name: "Kids & Magical Novelties",
    nameTa: "கிட்ஸ் ஸ்பெஷல்",
    slug: "kids-special",
    tagline: "Chittu Puttu, Helicopters, Butterflies and Rainbow Smoke",
    description: "Fun, low-sound novelties designed for children's enjoyment.",
    accent: "#00D26A",
    icon: "smile",
    imageUrl: "/categories/kids-special.jpg",
  },
  {
    name: "Gift Boxes",
    nameTa: "கிஃப்ட் பாக்ஸ்",
    slug: "gift-boxes",
    tagline: "Family, Royal & Corporate Deepavali Hampers (25 to 100 items)",
    description: "Curated festival packages containing a balanced mix across all categories.",
    accent: "#D4AF37",
    icon: "package",
    imageUrl: "/categories/gift-boxes.jpg",
  },
];

export const SEED_PRODUCTS: Record<string, [string, number, string, number, string?, string?][]> = {
  "single-sound": [
    ["2.75″ Kuruvi Crackers", 40, "1 pkt (5 pcs)", 5, "B", "/products/single-sound/kuruvi.jpg"],
    ["3.5″ Lakshmi Crackers", 70, "1 pkt (5 pcs)", 5, "B", "/products/single-sound/kuruvi.jpg"],
    ["4″ Lakshmi Crackers", 90, "1 pkt (5 pcs)", 5, "F", "/products/single-sound/gold-lakshmi.jpg"],
    ["2 Sound Crackers", 150, "1 pkt (5 pcs)", 5, "", "/products/single-sound/2-sound.jpg"],
    ["4″ Hulk / Harry Potter Deluxe", 160, "1 pkt (5 pcs)", 5, "N", "/products/single-sound/hulk-4.jpg"],
    ["Gold Lakshmi Deluxe", 170, "1 pkt (5 pcs)", 5, "P", "/products/single-sound/gold-lakshmi.jpg"],
    ["5″ Hulk / Vikram Mega Deluxe", 225, "1 pkt (5 pcs)", 5, "PN", "/products/single-sound/hulk-5.jpg"],
  ],

  "flower-pots": [
    ["Flower Pot Small", 250, "1 box (10 pcs)", 10, "B", "/products/flower-pots/dass-deluxe.jpg"],
    ["Flower Pot Big", 300, "1 box (10 pcs)", 10, "B", "/products/flower-pots/giant.jpg"],
    ["Flower Pot Special", 450, "1 box (10 pcs)", 10, "F", "/products/flower-pots/special.jpg"],
    ["Flower Pot Asoka", 600, "1 box (10 pcs)", 10, "F", "/products/flower-pots/asoka.jpg"],
    ["O-Yolo Super Prime", 800, "1 box (2 pcs)", 2, "P", "/products/flower-pots/oyolo.jpg"],
    ["Flower Pots Deluxe", 850, "1 box (5 pcs)", 5, "", "/products/flower-pots/dass-deluxe.jpg"],
    ["Color Koti Green", 960, "1 box (10 pcs)", 10, "N", "/products/flower-pots/giant.jpg"],
    ["Colour Koti Green Prime", 1150, "1 box (10 pcs)", 10, "PN", "/products/flower-pots/giant.jpg"],
  ],

  fountains: [
    ["Flower Pot Small Prime", 300, "1 box (10 pcs)", 10, "", "/products/fountains/saravanavel-super-deluxe.jpg"],
    ["Flower Pot Big Prime", 400, "1 box (10 pcs)", 10, "", "/products/fountains/saravanavel-super-deluxe.jpg"],
    ["Flower Pot Special Prime", 600, "1 box (10 pcs)", 10, "", "/products/fountains/saravanavel-super-deluxe.jpg"],
    ["Flower Pot Super Deluxe Prime", 750, "1 box (2 pcs)", 2, "", "/products/fountains/saravanavel-super-deluxe.jpg"],
    ["Flower Pot Giant Prime", 875, "1 box (10 pcs)", 10, "F", "/products/fountains/saravanavel-super-deluxe.jpg"],
    ["Jersey Fountain Prime", 900, "1 box (5 pcs)", 5, "", "/products/fountains/jet-fountain.jpg"],
    ["Flower Pot Asoka Prime", 975, "1 box (10 pcs)", 10, "", "/products/fountains/saravanavel-super-deluxe.jpg"],
    ["Tri Colour Fountain", 995, "1 box (5 pcs)", 5, "F", "/products/fountains/tri-colors.png"],
    ["Barat Koti MORI Prime", 1100, "1 box (2 pcs)", 2, "", "/products/fountains/mori-barat-koti.jpg"],
    ["Tri Color Fountain Prime", 1250, "1 box (5 pcs)", 5, "", "/products/fountains/tri-colors.png"],
    ["Mayajaal Five Colour Cone", 1400, "1 box (5 pcs)", 5, "P", "/products/fountains/tri-colors.png"],
    ["Pink Colour Koti Prime", 2300, "1 box (1 pcs)", 1, "PN", "/products/fountains/mori-barat-koti.jpg"],
    ["Colour Koti Deluxe MORI Brand", 2400, "1 box (10 pcs)", 10, "P", "/products/fountains/mori-barat-koti.jpg"],
    ["Varnajal Tri Colour VANITHA Brand", 2750, "1 box (10 pcs)", 10, "P", "/products/fountains/tri-colors.png"],
    ["Pink Colour Cone VANITHA Brand", 2995, "1 box (10 pcs)", 10, "P", "/products/fountains/mori-barat-koti.jpg"],
    ["Web Coin", 350, "1 box (1 pcs)", 1, ""],
    ["Disco Shower 5in1", 450, "1 box (5 pcs)", 5, "B"],
    ["Star Pots 5in1", 475, "1 box (5 pcs)", 5, ""],
    ["Tom & Jerry 5in1", 745, "1 box (5 pcs)", 5, "B"],
    ["Angry Birds 5 in 1", 1245, "1 box (5 pcs)", 5, "F"],
    ["Tango Multicolour 5in1", 1250, "1 box (1 pcs)", 1, ""],
    ["Tin Orange Crackling", 400, "1 pcs", 1, ""],
    ["Tin Green Grapes Crackling", 400, "1 pcs", 1, ""],
    ["Tin Silver Star Crackling", 400, "1 pcs", 1, ""],
    ["Tin Water Melon Crackling", 400, "1 pcs", 1, ""],
    ["Star Light 5 pcs", 450, "1 box (5 pcs)", 5, ""],
    ["2″ Sunfeast / Mayajal Red", 750, "1 box (5 pcs)", 5, ""],
    ["2″ Sunfeast / Mayajal Green", 750, "1 box (5 pcs)", 5, ""],
    ["2″ Sunfeast / Mayajal Silver", 750, "1 box (5 pcs)", 5, ""],
    ["2″ Sunfeast / Mayajal Gold", 750, "1 box (5 pcs)", 5, ""],
    ["2″ Sunfeast / Mayajal Red & Green", 750, "1 box (5 pcs)", 5, ""],
    ["Tik Tok Crackling 3 pcs", 625, "1 box (3 pcs)", 3, ""],
    ["Manny Toy Multicolour Fountain", 1250, "1 box (3 pcs)", 3, ""],
    ["Buji Toy Green Fountain", 1250, "1 box (3 pcs)", 3, ""],
    ["Dragon Toy Silver Fountain", 1250, "1 box (3 pcs)", 3, ""],
    ["Water Queen Falls", 700, "1 pcs", 1, "F"],
    ["6000 Crackling Fountain", 745, "1 box (1 pcs)", 1, ""],
    ["Cock Fight", 825, "1 box (2 pcs)", 2, ""],
    ["Ultra Voltage", 825, "1 box (2 pcs)", 2, ""],
    ["Lollipops Shower", 825, "1 box (2 pcs)", 2, ""],
    ["Mojito Shower", 825, "1 box (2 pcs)", 2, ""],
    ["Peacock Feather", 825, "1 box (2 pcs)", 2, ""],
    ["Pride Popcorn", 825, "1 box (2 pcs)", 2, ""],
    ["Gold Feast 2in1", 825, "1 box (5 pcs)", 5, ""],
    ["King Fish 2in1", 825, "1 box (1 pcs)", 1, ""],
    ["Twins Tone 2in1", 825, "1 box (1 pcs)", 1, ""],
    ["Trolls 2in1", 825, "1 box (1 pcs)", 1, ""],
    ["Poppy 3in1 (Rose, Green, Red)", 1000, "1 box (1 pcs)", 1, ""],
    ["Miss Rich 3in1 (Green, White, Red)", 1000, "1 box (1 pcs)", 1, ""],
    ["Kelly 3in1 (R&G, Rose & Crackling)", 1000, "1 box (1 pcs)", 1, ""],
    ["Wonders 3in1 Max", 1300, "1 box (1 pcs)", 1, "P"],
    ["Spooky 3in1 Fountain", 1800, "1 box (5 pcs)", 5, "P"],
    ["Bada Tin Jolly Bobby Mocktail 1 pcs", 995, "1 box (1 pcs)", 1, ""],
    ["Water Queen Falls Special", 1050, "1 pcs", 1, "P"],
    ["Mojito / Jolly Bobby Mega Crackling", 2100, "1 box (3 pcs)", 3, "P"],
    ["Infinity Crackling Fountain 3 pcs", 2100, "1 box (3 pcs)", 3, "P"],
    ["Bada Tin Jolly Bobby Mocktail 3 pcs", 2995, "1 box (3 pcs)", 3, "P"],
  ],

  "ground-chakkar": [
    ["Chakkar Asoka", 300, "1 box (10 pcs)", 10, "B"],
    ["Chakkar Special E", 325, "1 box (10 pcs)", 10, ""],
    ["Chakkar Special", 475, "1 box (10 pcs)", 10, "F"],
    ["Chakkar Asoka Prime", 650, "1 box (10 pcs)", 10, ""],
    ["Win Wheel Speed", 675, "1 box (10 pcs)", 10, ""],
    ["Chakkar Deluxe", 710, "1 box (10 pcs)", 10, "F"],
    ["Wire Chakkar", 750, "1 box (10 pcs)", 10, "B"],
    ["Chakkar Deluxe Prime", 900, "1 box (10 pcs)", 10, "P"],
    ["Whizz Chakkar", 545, "1 box (2 pcs)", 2, ""],
    ["Lotus 4×4 Wheel", 600, "1 box (3 pcs)", 3, ""],
    ["Win Wheel Mini Prime", 700, "1 box (10 pcs)", 10, ""],
    ["4×4 Wheels", 800, "1 box (5 pcs)", 5, "F"],
    ["Win Wheel Max Prime", 895, "1 box (10 pcs)", 10, ""],
    ["Wire Chakkar Prime", 975, "1 box (10 pcs)", 10, "P"],
    ["Spinner Green Color", 1050, "1 box (6 pcs)", 6, ""],
    ["Win Wheel Super Prime", 1100, "1 box (10 pcs)", 10, ""],
    ["Planet Wheeling Show", 1150, "1 box (2 pcs)", 2, "P"],
  ],

  "bijili-crackers": [
    ["Red Bijili Prime 50", 125, "1 bag (50 pcs)", 50, "B"],
    ["Super Stripped Bijili 50", 185, "1 bag (50 pcs)", 50, ""],
    ["Red Bijili Prime 100", 225, "1 bag (100 pcs)", 100, "B"],
    ["Super Stripped Bijili 100", 375, "1 bag (100 pcs)", 100, "F"],
    ["Old is Gold – Ola Vedi 25 pcs", 875, "1 box (25 pcs)", 25, "P"],
  ],

  "wala-crackers": [
    ["90 Watts Digital Wala", 750, "1 box (3 pcs)", 3, "B"],
    ["28 Giant Effects", 750, "1 box (5 box)", 5, "F"],
    ["1000 Wala Effects", 900, "1 box (1 pcs)", 1, "P"],
  ],

  bombs: [
    ["Hydro Bomb", 375, "1 box (10 pcs)", 10, "B"],
    ["King of King Bomb", 495, "1 box (10 pcs)", 10, "B"],
    ["Trace Bomb", 600, "1 box (10 pcs)", 10, "F"],
    ["Dianosaur Bomb", 1050, "1 box (10 pcs)", 10, "P"],
    ["Digital Bomb", 1100, "1 box (10 pcs)", 10, "PN"],
  ],

  "paper-flash": [
    ["Money in Bank", 675, "1 box (3 pcs)", 3, "F"],
    ["Money Heist Paper Blast", 1100, "1 box (2 pcs)", 2, "B"],
    ["Black Money Flash 5 pcs", 1200, "1 box (5 pcs)", 5, "PN"],
  ],

  rockets: [
    ["Colour Rocket", 350, "1 box (10 pcs)", 10, "B"],
    ["Rocket Bomb", 400, "1 box (10 pcs)", 10, "F"],
    ["Musical Rocket", 750, "1 box (5 pcs)", 5, "F"],
    ["Whistling Rocket Multicolour", 800, "1 box (5 pcs)", 5, "P"],
    ["Whistling Rocket", 800, "1 box (10 pcs)", 10, "B"],
  ],

  "twinkling-star": [
    ["1½″ Twinkling Star", 120, "1 box (10 pcs)", 10, "B"],
    ["4″ Twinkling Star", 300, "1 box (10 pcs)", 10, "F"],
    ["Rope Pink Color", 900, "1 box (4 pcs)", 4, "P"],
  ],

  candles: [
    ["Ultra Colour Pencil", 325, "1 box (3 pcs)", 3, "B"],
    ["Jelly Bean Pencil", 475, "1 box (3 pcs)", 3, ""],
    ["Navrang Tricolor Pencil", 675, "1 box (5 pcs)", 5, "F"],
    ["Magic Light Green Crackling", 750, "1 box (3 pcs)", 3, ""],
    ["Fire Light Gold Crackling", 750, "1 box (3 pcs)", 3, ""],
    ["Water Light Silver Crackling", 750, "1 box (3 pcs)", 3, ""],
    ["Hi-Light Red & Green", 750, "1 box (3 pcs)", 3, ""],
    ["Vio Violet Torches", 900, "1 box (2 pcs)", 2, "P"],
  ],

  lighters: [
    ["Selfie Stick", 600, "1 box (5 pcs)", 5, "B"],
    ["5G Five Colour Flash Stick", 600, "1 box (1 pcs)", 1, "F"],
    ["Top Gun", 595, "1 box (5 pcs)", 5, ""],
    ["Magic Wand Water Fall", 950, "1 box (1 pcs)", 1, "P"],
    ["Cricket Bat and Ball", 1150, "1 box (1 pcs)", 1, "N"],
    ["Tiny Gun", 1995, "1 box (6 pcs)", 6, "PN"],
  ],

  "peacock-fountain": [
    ["Peacock 3 Wings", 700, "1 box (1 pcs)", 1, "B"],
    ["Peacock Tails", 950, "1 box (2 pcs)", 2, "F"],
    ["Bada Peacock", 1995, "1 box (1 pcs)", 1, "P"],
  ],

  novelties: [
    ["Race Car 2 Pcs", 1050, "1 box (2 pcs)", 2, "N"],
    ["Rising Effects Multicolour Balls 1 Pcs", 950, "1 pcs", 1, ""],
    ["Caterpillar", 1260, "1 box (2 pcs)", 2, ""],
    ["Mini Pot Mix 5 Colours", 1555, "1 box (5 pcs)", 5, ""],
    ["Super Stick", 2250, "1 box (6 pcs)", 6, ""],
    ["Crystal Spin & Flies", 3750, "1 pcs", 1, "P"],
    ["Rising Effects Multicolour Balls", 9750, "1 box (6 pcs)", 6, "P"],
    ["Purple Little Dove", 350, "1 box (1 pcs)", 1, ""],
    ["Gold Little Dove", 350, "1 box (1 pcs)", 1, ""],
    ["Silver Little Dove", 350, "1 box (1 pcs)", 1, ""],
    ["Amber Little Dove", 350, "1 box (1 pcs)", 1, ""],
    ["Lemon Tree 2in1", 645, "1 box (1 pcs)", 1, ""],
    ["Rio Wheel Pink & Orange", 1100, "1 box (5 pcs)", 5, ""],
    ["Tora Tora Crackling Ayyan brand", 2000, "1 box (5 box)", 5, "P"],
    ["Star Buds Green Glittering", 940, "1 box (5 pcs)", 5, ""],
    ["Pinkie Pie Pink Fountain", 950, "1 box (1 pcs)", 1, ""],
    ["Blossom Violet Fountain", 950, "1 box (1 pcs)", 1, ""],
    ["Euro Star 6in1 Chakkar Ajanta Brand", 950, "1 box (2 pcs)", 2, ""],
    ["Mini Pearl", 900, "1 box (5 pcs)", 5, ""],
    ["Rim Jhim 5 pcs", 1100, "1 box (5 box)", 5, ""],
    ["Magic Star 5 Pcs", 2000, "1 box (5 pcs)", 5, ""],
    ["Dazzle Deluxe", 2750, "1 box (4 pcs)", 4, "P"],
    ["Tik Tok", 1050, "1 box (1 pcs)", 1, ""],
    ["Cracker Jack", 1050, "1 box (1 pcs)", 1, ""],
    ["Jelly Belly", 1050, "1 box (1 pcs)", 1, ""],
    ["Rainy Shiny", 1050, "1 box (1 pcs)", 1, ""],
  ],

  "sky-shots": [
    ["Paanch Chamak 5 Varieties", 700, "1 box (5 pcs)", 5, "B"],
    ["Penta Magic 5 in 1", 700, "1 box (5 pcs)", 5, ""],
    ["1″ Chotta Sky Display", 200, "1 box (1 pcs)", 1, "B"],
    ["2″ Fancy Sky Display", 500, "1 box (1 pcs)", 1, "B"],
    ["2″ Turbo Sky Display 3 Pcs", 1475, "1 box (3 pcs)", 3, ""],
    ["3.5″ Smash Sky Display", 1475, "1 box (1 pcs)", 1, "F"],
    ["3.5″ Tesco Sky Display", 1495, "1 box (1 pcs)", 1, ""],
    ["3.5″ HiFi Sky Display", 1495, "1 box (1 pcs)", 1, ""],
    ["3.5″ Drinks Sky Display", 1600, "1 box (1 pcs)", 1, ""],
    ["4″ Mega Sky Display", 1975, "1 box (1 pcs)", 1, "F"],
    ["4″ Double Ball Sky Display", 2200, "1 box (1 pcs)", 1, "P"],
    ["5″ Deluxe Sky Display", 4400, "1 box (1 pcs)", 1, "P"],
    ["3.5″ Nayagara Falls", 1600, "1 box (1 pcs)", 1, "F"],
    ["3.5″ Seven Step Wedding Series", 1800, "1 box (1 pcs)", 1, "F"],
    ["4″ Seven Step Sky Display", 2400, "1 box (1 pcs)", 1, "P"],
    ["3.5″ Nayagara Falls 2pcs", 3200, "1 box (2 pcs)", 2, "P"],
    ["3.5″ The Incredible Sky Display", 2000, "1 box (3 pcs)", 3, "P"],
    ["3″ Turbo Sky Display", 1475, "1 box (1 pcs)", 1, ""],
    ["4″ Turbo Sky Display", 2250, "1 box (1 pcs)", 1, ""],
    ["4″ Turbo Sky Display 2 Pcs", 4495, "1 box (2 pcs)", 2, "P"],
    ["5″ Jumbo Sky Display 2 Pcs", 5250, "1 box (2 pcs)", 2, "P"],
    ["5″ Purple Rain", 8500, "1 box (1 pcs)", 1, "P"],
    ["Jungle Party Niagara Falls", 8500, "1 box (1 pcs)", 1, "P"],
    ["7 Shot", 450, "1 box (5 pcs)", 5, "B"],
    ["12 Shot Flash Green", 750, "1 box (1 pcs)", 1, "F"],
    ["30 Peacock Bloom Multicolour Shot", 2250, "1 box (1 pcs)", 1, "F"],
    ["30 Multi Color Shot Ultra", 2250, "1 box (1 pcs)", 1, ""],
    ["30 Multi Color Shot Prime", 2750, "1 box (1 pcs)", 1, ""],
    ["60 Multi Colour Shot Ultra", 4800, "1 box (1 pcs)", 1, "P"],
    ["Hand Shot Multicolour", 6000, "1 box (1 pcs)", 1, "P"],
    ["120 Multi Colour Shot Ultra", 9600, "1 box (1 pcs)", 1, "P"],
    ["240 Multi Colour Shot Ultra", 19000, "1 box (1 pcs)", 1, "P"],
    ["12 Whistling Shot", 1775, "1 box (1 pcs)", 1, ""],
    ["30 Multi Color Shot with Crackling Prime", 3245, "1 box (1 pcs)", 1, "P"],
    ["25 Whistling Shot", 4000, "1 box (1 pcs)", 1, "P"],
    ["60 Shot Multi Color with Crackling Pro", 6500, "1 box (1 pcs)", 1, "P"],
    ["5X10 Holi Celebration", 12500, "1 box (1 pcs)", 1, "P"],
    ["5X10 Wild Celebration", 14000, "1 box (1 pcs)", 1, "P"],
    ["5X10 Dragon Mines", 14500, "1 box (1 pcs)", 1, "P"],
    ["10×10 Sizziling Shot", 17500, "1 box (1 pcs)", 1, "P"],
    ["10X10 Light of Thunder", 22500, "1 box (1 pcs)", 1, "P"],
  ],

  sparklers: [
    ["10cm Electric", 90, "1 box (10 pcs)", 10, "B"],
    ["10cm Crackling", 100, "1 box (10 pcs)", 10, "B"],
    ["12cm Electric", 130, "1 box (10 pcs)", 10, "B"],
    ["12cm Crackling", 140, "1 box (10 pcs)", 10, ""],
    ["15cm Electric", 200, "1 box (10 pcs)", 10, "F"],
    ["30cm Electric", 200, "1 box (5 pcs)", 5, "F"],
    ["15cm Crackling", 225, "1 box (10 pcs)", 10, ""],
    ["30cm Crackling", 225, "1 box (5 pcs)", 5, ""],
    ["15cm Green", 250, "1 box (10 pcs)", 10, ""],
    ["30cm Green", 275, "1 box (5 pcs)", 5, ""],
    ["15cm Red", 275, "1 box (10 pcs)", 10, ""],
    ["30cm Red", 300, "1 box (5 pcs)", 5, ""],
    ["50cm Electric", 800, "1 box (5 pcs)", 5, "P"],
    ["50cm Crackling", 900, "1 box (5 pcs)", 5, "P"],
    ["Rotating Sparklers Premium", 1000, "1 box (1 pcs)", 1, "P"],
  ],

  "match-boxes": [
    ["Classic 5 in 1", 750, "1 box (10 box)", 10, "B"],
    ["Classic Top 10 in 1", 1250, "1 box (10 box)", 10, "F"],
  ],

  "hunters-gun": [
    ["MIB Ring Cap with Gun", 550, "1 box (1 pcs)", 1, "B"],
    ["Pirates Ring Cap with Gun", 900, "1 box (1 pcs)", 1, "P"],
  ],

  "kids-special": [
    ["Chittu Puttu – Kit Kat", 150, "1 box (10 pcs)", 10, "B"],
    ["Photo Flash", 300, "1 box (5 pcs)", 5, "F"],
    ["Big Chittu Puttu – Tim Tam", 350, "1 box (10 pcs)", 10, "B"],
    ["Helicopter Red & Green", 375, "1 box (5 pcs)", 5, "F"],
    ["Butterfly Red & Green", 400, "1 box (10 pcs)", 10, ""],
    ["Dancing Butterfly Multicolour", 450, "1 box (10 pcs)", 10, "F"],
    ["Bambara Spinner Prime", 495, "1 box (10 pcs)", 10, ""],
    ["Pappu Shower", 600, "1 box (2 pcs)", 2, ""],
    ["Rainbow Color Smoke", 650, "1 box (3 pcs)", 3, "P"],
    ["Siren Big 3 pcs", 750, "1 box (3 pcs)", 3, ""],
    ["Colour Flash (Red, Green, Silver)", 2225, "1 box (6 pcs)", 6, "P"],
  ],

  "gift-boxes": [
    ["Mayilon Mini Gift Box (25 Items)", 1450, "1 Box", 25, "FB"],
    ["Family Festival Box (45 Items)", 3200, "1 Box", 45, "FBP"],
    ["Royal Deepavali Hamper (75 Items)", 6400, "1 Box", 75, "FP"],
    ["Corporate Luxury Box (100 Items)", 11500, "1 Box", 100, "PN"],
    ["Kids Joy Box (30 Items)", 1850, "1 Box", 30, "B"],
  ],
};

export const SEED_REVIEWS = [
  {
    name: "Karthik Subramanian",
    location: "Chennai, Tamil Nadu",
    rating: 5,
    title: "Factory price, 80% discount quality",
    body: "Ordered a ₹28,000 estimate for our apartment Deepavali. Packing was flawless, 80% off MRP pricing is genuine and sky shots were show-grade.",
  },
  {
    name: "Priya Ramesh",
    location: "Coimbatore, Tamil Nadu",
    rating: 5,
    title: "The kids box & sparklers are brilliant",
    body: "Low sound items actually are low sound. Sparklers and flower pots are genuine Sivakasi quality. Will reorder every year.",
  },
  {
    name: "Mohan Reddy",
    location: "Hyderabad, Telangana",
    rating: 5,
    title: "Best dealer & wholesale pricing",
    body: "I run 3 retail outlets. The 80% discount plus transport coordination saved me nearly 20% versus my previous supplier in Sivakasi.",
  },
  {
    name: "Anitha Vasanth",
    location: "Madurai, Tamil Nadu",
    rating: 5,
    title: "Wedding multi-shot was cinematic",
    body: "We booked the 120 multi color shot ultra for a wedding entry. The team advised on safety distance and the sky show looked stunning.",
  },
  {
    name: "Rajesh Kumar",
    location: "Bengaluru, Karnataka",
    rating: 4,
    title: "Smooth estimate process",
    body: "Submitted estimate at midnight, got a WhatsApp confirmation and a call by 10am. Transparent transport charge — no hidden costs.",
  },
  {
    name: "Fathima Noor",
    location: "Kochi, Kerala",
    rating: 5,
    title: "Genuine Sivakasi stock",
    body: "Everything arrived sealed with batch codes and safety leaflets. This is what factory-direct should feel like.",
  },
];
