export const IMAGE_POOL = [
  "https://images.pexels.com/photos/29440437/pexels-photo-29440437.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/31210634/pexels-photo-31210634.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/36745051/pexels-photo-36745051.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/5302663/pexels-photo-5302663.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/38128369/pexels-photo-38128369.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/12745603/pexels-photo-12745603.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/31196818/pexels-photo-31196818.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/37125137/pexels-photo-37125137.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/12745602/pexels-photo-12745602.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/31210664/pexels-photo-31210664.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
];

export type SeedCategory = {
  name: string;
  nameTa: string;
  slug: string;
  tagline: string;
  description: string;
  accent: string;
  icon: string;
  imageUrl: string;
};

export const SEED_CATEGORIES: SeedCategory[] = [
  {
    name: "One Sound / 2 Sound Crackers",
    nameTa: "ஒற்றை & இரட்டை வெடி",
    slug: "single-sound",
    tagline: "Classic Sivakasi Lakshmi, Kuruvi & 2 Sound crackers",
    description: "Traditional single and double report crackers with sharp decibel report.",
    accent: "#FF3131",
    icon: "volume",
    imageUrl: "/categories/single-sound.jpg",
  },
  {
    name: "Bijili Crackers",
    nameTa: "பிஜிலி வெடி",
    slug: "bijili-crackers",
    tagline: "Red and Stripped bijili 100 bags",
    description: "Crisp crackling bijilis packed in 100 piece bags.",
    accent: "#FF3131",
    icon: "zap",
    imageUrl: "/categories/bijili-crackers.jpg",
  },
  {
    name: "SOUND CRACKERS",
    nameTa: "சரவெடி & வெடிகள்",
    slug: "sound-crackers",
    tagline: "28 Chorsa, 56 Giant & 100 to 10k Watts crackers",
    description: "High-decibel traditional crackers and festival celebration chains.",
    accent: "#FF3131",
    icon: "volume-2",
    imageUrl: "/categories/wala-crackers.jpg",
  },
  {
    name: "Ground Chakkars",
    nameTa: "நிலச்சக்கரம்",
    slug: "ground-chakkar",
    tagline: "Ground Chakkar Big, Special, Deluxe and Spinners",
    description: "High-rpm ground wheels and spinners for kids and families.",
    accent: "#00D26A",
    icon: "disc",
    imageUrl: "/categories/ground-chakkar.jpg",
  },
  {
    name: "Twinkling Stars",
    nameTa: "ட்விங்க்ளிங் ஸ்டார்",
    slug: "twinkling-star",
    tagline: "1½' & 4' Twinkling Star ropes",
    description: "Continuous twinkling stars and star ropes.",
    accent: "#F5D982",
    icon: "star",
    imageUrl: "/categories/twinkling-star.jpg",
  },
  {
    name: "Flower Pots",
    nameTa: "பூச்சட்டி",
    slug: "flower-pots",
    tagline: "Flower Pots Big, Special, Asoka & Colour Kotti",
    description: "Classic high-rise golden and silver fountains with low smoke composition.",
    accent: "#D4AF37",
    icon: "sparkles",
    imageUrl: "/categories/flower-pots.jpg",
  },
  {
    name: "Rockets",
    nameTa: "ராக்கெட்",
    slug: "rockets",
    tagline: "Musical Rocket and Rocket Bomb",
    description: "High-flying rockets with whistling sound and bright canopy bursts.",
    accent: "#FF8C00",
    icon: "rocket",
    imageUrl: "/categories/rockets.jpg",
  },
  {
    name: "Pencils",
    nameTa: "பென்சில்ஸ்",
    slug: "candles",
    tagline: "Nayagara Falls Handle pencils & Hi tech pencil",
    description: "Multi-color fountain handle pencils.",
    accent: "#00D26A",
    icon: "flame",
    imageUrl: "/categories/candles.jpg",
  },
  {
    name: "Bombs",
    nameTa: "பாம் வகைகள்",
    slug: "bombs",
    tagline: "King Bomb, Classic Bomb, Jurassic & Paper Bombs",
    description: "High-decibel sound bombs with heavy casing and water-resistant fuse.",
    accent: "#FF3131",
    icon: "bomb",
    imageUrl: "/categories/bombs.jpg",
  },
  {
    name: "Fountains",
    nameTa: "ஃபவுண்டன் வகைகள்",
    slug: "fountains",
    tagline: "Tom & Jerry, Peacock, Water Queen & Novelty Fountains",
    description: "Vibrant shower cones, multi-step fountains and tri-color pyro fountain displays.",
    accent: "#FF8C00",
    icon: "flame",
    imageUrl: "/categories/fountains.jpg",
  },
  {
    name: "KIDS SPECIAL",
    nameTa: "குழந்தைகளுக்கான ஸ்பெஷல்",
    slug: "kids-special",
    tagline: "Elephant Fountain, Race Car, Drone, AK 47 Gun & Novelties",
    description: "Fun, exciting and child-friendly fireworks for joyful celebrations.",
    accent: "#00D26A",
    icon: "sparkles",
    imageUrl: "/categories/kids-special.jpg",
  },
  {
    name: "Aerial Shots",
    nameTa: "வான வெடி",
    slug: "sky-shots",
    tagline: "Chotta Fancy, 2″ Fancy, 3.5″ Smash & Nayagara Falls",
    description: "Single sky displays and aerial shells.",
    accent: "#0057FF",
    icon: "rocket",
    imageUrl: "/categories/sky-shots.jpg",
  },
  {
    name: "Multi Shots",
    nameTa: "மல்டி ஷாட்ஸ்",
    slug: "multi-shots",
    tagline: "15 to 240 Shots Colour sky repeaters",
    description: "Aerial multi-color sky repeaters and celebration set outs.",
    accent: "#0057FF",
    icon: "rocket",
    imageUrl: "/categories/sky-shots.jpg",
  },
  {
    name: "PREMIUM FOUNTAINS",
    nameTa: "பிரீமியம் ஃபவுண்டன்",
    slug: "premium-fountains",
    tagline: "Exclusive HAND SHOT New & Luxury fireworks",
    description: "Luxury pyro fountains with rich sparkling color displays.",
    accent: "#D4AF37",
    icon: "flame",
    imageUrl: "/categories/peacock-fountain.jpg",
  },
  {
    name: "Sparklers",
    nameTa: "மத்தாப்பு",
    slug: "sparklers",
    tagline: "7cm to 50cm Electric, Colour, Green & Red sparklers",
    description: "Child-safe sparklers with bright light and low smoke emission.",
    accent: "#F5D982",
    icon: "wand",
    imageUrl: "/categories/sparklers.jpg",
  },
  {
    name: "Colour Matches & Novelties",
    nameTa: "தீப்பெட்டி & ஃபேன்சி",
    slug: "novelties",
    tagline: "Roll Caps, Black Serpents, Super Matches & Laptop Mega Matches",
    description: "Match boxes, caps, serpents and novelties.",
    accent: "#FF8C00",
    icon: "gift",
    imageUrl: "/categories/novelties.jpg",
  },
  {
    name: "Gift Boxes",
    nameTa: "கிஃப்ட் பாக்ஸ்",
    slug: "gift-boxes",
    tagline: "25 to 50 Items Family & Festive Packs",
    description: "Curated festival packages containing a balanced mix across all categories.",
    accent: "#D4AF37",
    icon: "package",
    imageUrl: "/categories/gift-boxes.jpg",
  },
];

export const SEED_PRODUCTS: Record<string, [string, number, string, number, string?, string?, number?][]> = {
  "single-sound": [
    ["2 3/4\" Kuruvi", 35, "1 Box", 5, "B", "/products/single-sound/kuruvi.jpg", 7],
    ["3 1/2\" Laxmi", 60, "1 Box", 5, "B", undefined, 12],
    ["4\" Laxmi", 80, "1 Box", 5, "F", "/products/single-sound/hulk-4.jpg", 16],
    ["4\" Deluxe Laxmi", 125, "1 Box", 5, "N", undefined, 25],
    ["4\" Gold Laxmi", 160, "1 Box", 5, "P", "/products/single-sound/gold-lakshmi.jpg", 32],
    ["5\" Laxmi", 240, "1 Box", 5, "PN", "/products/single-sound/hulk-5.jpg", 48],
    ["6\"Lion", 290, "1 Box", 5, "B", "/products/single-sound/2-sound.jpg", 58],
  ],

  "bijili-crackers": [
    ["Red Bijili 100", 250, "1 Bag (100 Pcs)", 100, "B", undefined, 30],
    ["Stripped Bijili 100", 225, "1 Bag (100 Pcs)", 100, "F", undefined, 45],
  ],

  "sound-crackers": [
    ["28 Chorsa", 125, "1 pocket", 28, "B", undefined, 25],
    ["56 Giant", 500, "1 pocket", 56, "F", undefined, 100],
    ["100 watts", 150, "1 BOX", 1, "B", undefined, 30],
    ["200 Watts", 325, "1 BOX", 1, "B", undefined, 65],
    ["1k watts", 900, "1 BOX (10 PCS)", 10, "P", undefined, 180],
    ["2k watts", 1800, "1 BOX (10 PCS)", 10, "P", undefined, 360],
    ["5k watts", 4500, "1 BOX (10 PCS)", 10, "P", undefined, 900],
    ["10k watts", 9000, "1 BOX (10 PCS)", 10, "P", undefined, 1800],
  ],

  "ground-chakkar": [
    ["Ground Chakkar Big 10Pcs", 195, "1 Box (10 Pcs)", 10, "B", undefined, 39],
    ["Ground Chakkar Special", 340, "1 Box (10 Pcs)", 10, "F", undefined, 68],
    ["Ground Chakkar Deluxe", 550, "1 Box (10 Pcs)", 10, "P", undefined, 110],
    ["Spinner Deluxe", 850, "1 Box (5 Pcs)", 5, "N", undefined, 170],
    ["Wire Chakkar", 1000, "1 BOX (10 PCS)", 10, "P", undefined, 200],
  ],

  "twinkling-star": [
    ["1 1/2' Twinkling Stars", 120, "1 Box (10 Pcs)", 10, "B", undefined, 24],
    ["4' Twinkling Stars", 325, "1 Box (10 Pcs)", 10, "F", undefined, 65],
  ],

  "flower-pots": [
    ["Flower Pots Big", 330, "1 Box (10 Pcs)", 10, "B", "/products/flower-pots/dass-deluxe.jpg", 66],
    ["Flower Pots Special", 440, "1 Box (10 Pcs)", 10, "F", "/products/flower-pots/special.jpg", 88],
    ["Flower Pots Asoka", 550, "1 Box (10 Pcs)", 10, "P", "/products/flower-pots/asoka.jpg", 110],
    ["Colour Kotti", 1000, "1 Box (10 Pcs)", 10, "N", undefined, 200],
    ["Colour Kotti Deluxe", 1575, "1 Box (10 Pcs)", 10, "PN", "/products/flower-pots/giant.jpg", 315],
  ],

  "rockets": [
    ["Rocket Bomb", 700, "1 Box (10 Pcs)", 10, "F", undefined, 140],
    ["Musical Rocket", 1000, "1 Box (10 Pcs)", 10, "B", undefined, 200],
  ],

  "candles": [
    ["Hi tech pencil", 500, "1 BOX", 5, "B", undefined, 100],
    ["Nayagara Falls Handle", 820, "1 Box (5 Pcs)", 5, "F", undefined, 164],
  ],

  "bombs": [
    ["King Bomb", 550, "1 Box (10 Pcs)", 10, "B", undefined, 110],
    ["Classic Bomb", 650, "1 Box (10 Pcs)", 10, "F", undefined, 130],
    ["Jurassic Bomb Or Digital Bomb", 1050, "1 Box (10 Pcs)", 10, "P", undefined, 210],
    ["Paper Bomb 1/4 Kg", 225, "1 Box", 1, "B", undefined, 45],
    ["Paper Bomb 1/2 Kg", 450, "1 Box", 1, "F", undefined, 90],
    ["Paper Bomb 1 Kg", 900, "1 Box", 1, "P", undefined, 180],
  ],

  "fountains": [
    ["Tom and Jerry", 125, "1 Box (5 Pcs)", 5, "B", undefined, 25],
    ["Tricolour Fountain", 1400, "1 Box (5 Pcs)", 5, "P", "/products/fountains/tri-colors.png", 280],
    ["Colour Rain", 650, "1 Box (5 Pcs)", 5, "B", undefined, 130],
    ["Fox Star", 700, "1 Box", 5, "B", "/products/fountains/jet-fountain.jpg", 140],
    ["Sing Pop", 725, "1 Box", 5, "F", undefined, 145],
    ["Mega Siren", 900, "1 Box (3 Pcs)", 3, "F", undefined, 180],
    ["Mini Siren", 600, "1 Box (3 Pcs)", 3, "B", undefined, 120],
    ["Peacock Feather", 850, "1 Box (2 Pcs)", 2, "F", "/products/fountains/mori-barat-koti.jpg", 170],
    ["H2O Falls", 750, "1 Box (1 Pc)", 1, "B", undefined, 150],
    ["LION Fountain", 1250, "1 Box", 1, "P", undefined, 250],
    ["Water Queen", 750, "1 Box (1 Pc)", 1, "B", undefined, 150],
    ["Peacock Multicolour", 850, "1 Box (1 Pc)", 1, "F", undefined, 170],
    ["Bada Peacock", 1700, "1 Box (1 Pc)", 1, "P", undefined, 340],
    ["Colour Smoke", 650, "1 Box (3 Pcs)", 3, "B", undefined, 130],
    ["4x4 Whistling Wheel", 1100, "1 Box (3 Pcs)", 3, "F", undefined, 220],
    ["Lotus Wheel", 575, "1 Box (3 Pcs)", 3, "B", undefined, 115],
    ["Tin", 600, "1 Box (1 Pc)", 1, "B", undefined, 120],
  ],

  "kids-special": [
    ["Elephant Fountain", 1150, "1 Box", 1, "B", undefined, 230],
    ["Race Car", 1250, "1 Box (2 Pcs)", 2, "F", undefined, 250],
    ["GULFI", 1100, "1 BOX", 1, "B", undefined, 220],
    ["Murugar Vel special", 1100, "1 Box", 1, "F", undefined, 220],
    ["Drone", 775, "1 Box (5 Pcs)", 5, "F", undefined, 155],
    ["Helicopter", 500, "1 Box (5 Pcs)", 5, "B", undefined, 100],
    ["Free Fire Gun", 1750, "1 Box (2pc)", 2, "P", undefined, 350],
    ["Bambaram", 500, "1 Box (10 Pcs)", 10, "B", undefined, 100],
    ["Photo Flash", 300, "1 Box (5 Pcs)", 5, "B", undefined, 60],
    ["Insta Selfie", 675, "1 Box (5 Pcs)", 5, "F", undefined, 135],
    ["AK 47 GUN", 1000, "1 Box (5 Pcs)", 5, "F", undefined, 200],
    ["Bahubali Sword", 1000, "1 Box", 1, "P", undefined, 200],
  ],

  "sky-shots": [
    ["Chotta Fancy", 200, "1 Box (1 Pc)", 1, "B", undefined, 40],
    ["2\" Fancy", 550, "1 Box (1 Pc)", 1, "F", undefined, 110],
    ["2\" Fancy (3 Pc)", 1250, "1 Box (3 Pcs)", 3, "F", undefined, 250],
    ["3.5\" Single Smash", 1600, "1 Box (1 Pc)", 1, "P", undefined, 320],
    ["3.5\" Knight Series (2 Pc)", 2800, "1 Box (2 Pcs)", 2, "P", undefined, 560],
    ["3.5\" Double Ball", 2100, "1 Box (1 Pc)", 1, "P", undefined, 420],
    ["4\" Glory Series", 2300, "1 Box (1 Pc)", 1, "P", undefined, 460],
    ["4\"Twins (2pc)", 3950, "1 Box (2Pc)", 2, "P", undefined, 790],
    ["4\" Nayagara Falls Gold", 1900, "1 Box (1 Pc)", 1, "F", undefined, 380],
    ["4\" Nayagara Falls Crackling", 1900, "1 Box (1 Pc)", 1, "F", undefined, 380],
    ["Diwali Fabulous Celebration (12pipe)", 17500, "1 Box (1 Pc)", 1, "P", undefined, 3500],
  ],

  "multi-shots": [
    ["15 Shots Colour", 1000, "1 Box (1 Pc)", 1, "B", undefined, 200],
    ["30 Shots Colour", 2000, "1 Box (1 Pc)", 1, "F", undefined, 400],
    ["60 Shots Colour", 4000, "1 Box (1 Pc)", 1, "P", undefined, 800],
    ["120 Shots Colour", 8000, "1 Box (1 Pc)", 1, "P", undefined, 1600],
    ["240 Shots Colour", 16000, "1 Box (1 Pc)", 1, "P", undefined, 3200],
  ],

  "premium-fountains": [
    ["HAND SHOT New", 3000, "1 BOX (10 PCS)", 10, "P", undefined, 600],
  ],

  "sparklers": [
    ["7cm Electric Sparklers", 50, "1 Box (10 Pcs)", 10, "B", undefined, 10],
    ["7cm Colour Sparklers", 60, "1 Box (10 Pcs)", 10, "B", undefined, 12],
    ["7cm Green Sparklers", 70, "1 Box (10 Pcs)", 10, "B", undefined, 14],
    ["7cm Red Sparklers", 85, "1 Box (10 Pcs)", 10, "B", undefined, 17],
    ["10cm Electric Sparklers", 90, "1 Box (10 Pcs)", 10, "B", undefined, 18],
    ["10cm Colour Sparklers", 100, "1 Box (10 Pcs)", 10, "B", undefined, 20],
    ["10cm Green Sparklers", 115, "1 Box (10 Pcs)", 10, "F", undefined, 23],
    ["10cm Red Sparklers", 135, "1 Box (10 Pcs)", 10, "F", undefined, 27],
    ["12cm Electric Sparklers", 140, "1 Box (10 Pcs)", 10, "B", undefined, 28],
    ["12cm Colour Sparklers", 160, "1 Box (10 Pcs)", 10, "F", undefined, 32],
    ["12cm Green Sparklers", 180, "1 Box (10 Pcs)", 10, "F", undefined, 36],
    ["12cm Red Sparklers", 200, "1 Box (10 Pcs)", 10, "F", undefined, 40],
    ["15cm Electric Sparklers", 190, "1 Box (10 Pcs)", 10, "F", undefined, 38],
    ["15cm Colour Sparklers", 210, "1 Box (10 Pcs)", 10, "F", undefined, 42],
    ["15cm Green Sparklers", 230, "1 Box (10 Pcs)", 10, "F", undefined, 46],
    ["15cm Red Sparklers", 260, "1 Box (10 Pcs)", 10, "P", undefined, 52],
    ["30cm Electric Sparklers", 230, "1 Box (5 Pcs)", 5, "F", undefined, 46],
    ["30cm Colour Sparklers", 250, "1 Box (5 Pcs)", 5, "F", undefined, 50],
    ["30cm Green Sparklers", 270, "1 Box (5 Pcs)", 5, "F", undefined, 54],
    ["30cm Red Sparklers", 290, "1 Box (5 Pcs)", 5, "F", undefined, 58],
    ["50cm Electric Sparklers", 750, "1 Box (5 Pcs)", 5, "P", undefined, 150],
    ["50cm Colour Sparklers", 850, "1 Box (5 Pcs)", 5, "P", undefined, 170],
    ["50cm Red Sparklers", 1350, "1 Box (5 Pcs)", 5, "P", undefined, 270],
    ["50cm Green Sparklers", 1150, "1 Box (5 Pcs)", 5, "P", undefined, 230],
    ["Rotating Sparklers", 250, "1 Box", 5, "N", undefined, 50],
  ],

  "novelties": [
    ["ROLL CAPS", 300, "1 BOX (10 PCS)", 10, "B", undefined, 60],
    ["BLACK SERPENTS", 150, "1 Box", 10, "B", undefined, 30],
    ["SUPER MATCHES", 400, "1 Box (5 Pcs)", 5, "F", undefined, 80],
    ["LAPTOP MEGA 10 in 1 MATCHES", 850, "1 Box (10 Pcs)", 10, "P", undefined, 170],
  ],

  "gift-boxes": [
    ["30 Items (5pc Packs)", 2000, "1 Box", 30, "B", undefined, 400],
    ["40 Items (5pc Packs)", 3000, "1 Box", 40, "F", undefined, 600],
    ["50 items (5pc pack)", 4000, "1 box", 50, "P", undefined, 800],
    ["25 items (10pc Pack)", 1875, "1 Box", 25, "B", undefined, 375],
    ["30 items (10pc Pack)", 2200, "1 BOX (10 PCS)", 30, "F", undefined, 440],
    ["35items(10pc Pack)", 2700, "1 BOX", 35, "F", undefined, 540],
    ["42 items(10pc Pack)", 3000, "1 BOX", 42, "P", undefined, 600],
    ["50 items (10pc Pack)", 4000, "1 BOX", 50, "P", undefined, 800],
  ],
};

export const SEED_REVIEWS = [
  {
    name: "Karthik Subramanian",
    location: "Chennai, Tamil Nadu",
    rating: 5,
    title: "Factory price, 80% discount quality",
    body: "Ordered a ₹28,000 estimate for our apartment Deepavali. Packing was flawless, 80% off MRP pricing is genuine and sky shots were show-grade.",
  },
  {
    name: "Priya Ramesh",
    location: "Coimbatore, Tamil Nadu",
    rating: 5,
    title: "The kids box & sparklers are brilliant",
    body: "Low sound items actually are low sound. Sparklers and flower pots are genuine Sivakasi quality. Will reorder every year.",
  },
  {
    name: "Mohan Reddy",
    location: "Hyderabad, Telangana",
    rating: 5,
    title: "Best dealer & wholesale pricing",
    body: "I run 3 retail outlets. The 80% discount plus transport coordination saved me nearly 20% versus my previous supplier in Sivakasi.",
  },
  {
    name: "Anitha Vasanth",
    location: "Madurai, Tamil Nadu",
    rating: 5,
    title: "Wedding multi-shot was cinematic",
    body: "We booked the 120 multi color shot ultra for a wedding entry. The team advised on safety distance and the sky show looked stunning.",
  },
  {
    name: "Rajesh Kumar",
    location: "Bengaluru, Karnataka",
    rating: 4,
    title: "Smooth estimate process",
    body: "Submitted estimate at midnight, got a WhatsApp confirmation and a call by 10am. Transparent transport charge — no hidden costs.",
  },
  {
    name: "Fathima Noor",
    location: "Kochi, Kerala",
    rating: 5,
    title: "Genuine Sivakasi stock",
    body: "Everything arrived sealed with batch codes and safety leaflets. This is what factory-direct should feel like.",
  },
];
