export const IMAGE_POOL = [
  "https://images.pexels.com/photos/29440437/pexels-photo-29440437.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/31210634/pexels-photo-31210634.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/36745051/pexels-photo-36745051.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/5302663/pexels-photo-5302663.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/38128369/pexels-photo-38128369.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/12745603/pexels-photo-12745603.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/31196818/pexels-photo-31196818.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/37125137/pexels-photo-37125137.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/12745602/pexels-photo-12745602.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/31210664/pexels-photo-31210664.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
];

export type SeedCategory = {
  name: string;
  nameTa: string;
  slug: string;
  tagline: string;
  description: string;
  accent: string;
  icon: string;
  imageUrl: string;
};

export const SEED_CATEGORIES: SeedCategory[] = [
  {
    name: "One Sound / 2 Sound Crackers",
    nameTa: "ஒற்றை & இரட்டை வெடி",
    slug: "single-sound",
    tagline: "Classic Sivakasi Lakshmi, Kuruvi & 2 Sound crackers",
    description: "Traditional single and double report crackers with sharp decibel report.",
    accent: "#FF3131",
    icon: "volume",
    imageUrl: "/categories/single-sound.jpg",
  },
  {
    name: "Bijili Crackers",
    nameTa: "பிஜிலி வெடி",
    slug: "bijili-crackers",
    tagline: "Red and Stripped bijili 100 bags",
    description: "Crisp crackling bijilis packed in 100 piece bags.",
    accent: "#FF3131",
    icon: "zap",
    imageUrl: "/categories/bijili-crackers.jpg",
  },
  {
    name: "SOUND CRACKERS",
    nameTa: "சரவெடி & வெடிகள்",
    slug: "sound-crackers",
    tagline: "28 Chorsa, 56 Giant & 100 to 10k Watts crackers",
    description: "High-decibel traditional crackers and festival celebration chains.",
    accent: "#FF3131",
    icon: "volume-2",
    imageUrl: "/categories/wala-crackers.jpg",
  },
  {
    name: "Ground Chakkars",
    nameTa: "நிலச்சக்கரம்",
    slug: "ground-chakkar",
    tagline: "Ground Chakkar Big, Special, Deluxe and Spinners",
    description: "High-rpm ground wheels and spinners for kids and families.",
    accent: "#00D26A",
    icon: "disc",
    imageUrl: "/categories/ground-chakkar.jpg",
  },
  {
    name: "Twinkling Stars",
    nameTa: "ட்விங்க்ளிங் ஸ்டார்",
    slug: "twinkling-star",
    tagline: "1½' & 4' Twinkling Star ropes",
    description: "Continuous twinkling stars and star ropes.",
    accent: "#F5D982",
    icon: "star",
    imageUrl: "/categories/twinkling-star.jpg",
  },
  {
    name: "Flower Pots",
    nameTa: "பூச்சட்டி",
    slug: "flower-pots",
    tagline: "Flower Pots Big, Special, Asoka & Colour Kotti",
    description: "Classic high-rise golden and silver fountains with low smoke composition.",
    accent: "#D4AF37",
    icon: "sparkles",
    imageUrl: "/categories/flower-pots.jpg",
  },
  {
    name: "Rockets",
    nameTa: "ராக்கெட்",
    slug: "rockets",
    tagline: "Musical Rocket and Rocket Bomb",
    description: "High-flying rockets with whistling sound and bright canopy bursts.",
    accent: "#FF8C00",
    icon: "rocket",
    imageUrl: "/categories/rockets.jpg",
  },
  {
    name: "Pencils",
    nameTa: "பென்சில்ஸ்",
    slug: "candles",
    tagline: "Nayagara Falls Handle pencils & Hi tech pencil",
    description: "Multi-color fountain handle pencils.",
    accent: "#00D26A",
    icon: "flame",
    imageUrl: "/categories/candles.jpg",
  },
  {
    name: "Bombs",
    nameTa: "பாம் வகைகள்",
    slug: "bombs",
    tagline: "King Bomb, Classic Bomb, Jurassic & Paper Bombs",
    description: "High-decibel sound bombs with heavy casing and water-resistant fuse.",
    accent: "#FF3131",
    icon: "bomb",
    imageUrl: "/categories/bombs.jpg",
  },
  {
    name: "Fountains",
    nameTa: "ஃபவுண்டன் வகைகள்",
    slug: "fountains",
    tagline: "Tom & Jerry, Peacock, Water Queen & Novelty Fountains",
    description: "Vibrant shower cones, multi-step fountains and tri-color pyro fountain displays.",
    accent: "#FF8C00",
    icon: "flame",
    imageUrl: "/categories/fountains.jpg",
  },
  {
    name: "KIDS SPECIAL",
    nameTa: "குழந்தைகளுக்கான ஸ்பெஷல்",
    slug: "kids-special",
    tagline: "Elephant Fountain, Race Car, Drone, AK 47 Gun & Novelties",
    description: "Fun, exciting and child-friendly fireworks for joyful celebrations.",
    accent: "#00D26A",
    icon: "sparkles",
    imageUrl: "/categories/kids-special.jpg",
  },
  {
    name: "Aerial Shots",
    nameTa: "வான வெடி",
    slug: "sky-shots",
    tagline: "Chotta Fancy, 2″ Fancy, 3.5″ Smash & Nayagara Falls",
    description: "Single sky displays and aerial shells.",
    accent: "#0057FF",
    icon: "rocket",
    imageUrl: "/categories/sky-shots.jpg",
  },
  {
    name: "Multi Shots",
    nameTa: "மல்டி ஷாட்ஸ்",
    slug: "multi-shots",
    tagline: "15 to 240 Shots Colour sky repeaters",
    description: "Aerial multi-color sky repeaters and celebration set outs.",
    accent: "#0057FF",
    icon: "rocket",
    imageUrl: "/categories/sky-shots.jpg",
  },
  {
    name: "PREMIUM FOUNTAINS",
    nameTa: "பிரீமியம் ஃபவுண்டன்",
    slug: "premium-fountains",
    tagline: "Exclusive HAND SHOT New & Luxury fireworks",
    description: "Luxury pyro fountains with rich sparkling color displays.",
    accent: "#D4AF37",
    icon: "flame",
    imageUrl: "/categories/peacock-fountain.jpg",
  },
  {
    name: "Sparklers",
    nameTa: "மத்தாப்பு",
    slug: "sparklers",
    tagline: "7cm to 50cm Electric, Colour, Green & Red sparklers",
    description: "Child-safe sparklers with bright light and low smoke emission.",
    accent: "#F5D982",
    icon: "wand",
    imageUrl: "/categories/sparklers.jpg",
  },
  {
    name: "Colour Matches & Novelties",
    nameTa: "தீப்பெட்டி & ஃபேன்சி",
    slug: "novelties",
    tagline: "Roll Caps, Black Serpents, Super Matches & Laptop Mega Matches",
    description: "Match boxes, caps, serpents and novelties.",
    accent: "#FF8C00",
    icon: "gift",
    imageUrl: "/categories/novelties.jpg",
  },
  {
    name: "Gift Boxes",
    nameTa: "கிஃப்ட் பாக்ஸ்",
    slug: "gift-boxes",
    tagline: "25 to 50 Items Family & Festive Packs",
    description: "Curated festival packages containing a balanced mix across all categories.",
    accent: "#D4AF37",
    icon: "package",
    imageUrl: "/categories/gift-boxes.jpg",
  },
];

export const SEED_PRODUCTS: [string, string, number, string, number, string, string?, number?][] = [
  ["MYL-SND-01", "2 3/4\" Kuruvi", 35, "1 Box", 1, "", "/products/single-sound/kuruvi.jpg", 7],
  ["MYL-SND-02", "3 1/2\" Laxmi", 60, "1 Box", 1, "", "/categories/single-sound.jpg", 12],
  ["MYL-SND-03", "4\" Laxmi", 80, "1 Box", 1, "", "/products/single-sound/hulk-4.jpg", 16],
  ["MYL-SND-04", "4\" Deluxe Laxmi", 125, "1 Box", 1, "", "/categories/single-sound.jpg", 25],
  ["MYL-SND-05", "4\" Gold Laxmi", 160, "1 Box", 1, "", "/products/single-sound/gold-lakshmi.jpg", 32],
  ["MYL-SND-06", "5\" Laxmi", 240, "1 Box", 1, "", "/products/single-sound/hulk-5.jpg", 48],
  ["MYL-SND-07", "6\"Lion", 290, "1 Box", 1, "", "/products/single-sound/2-sound.jpg", 58],
  ["MYL-BJL-01", "Red Bijili 100", 250, "1 Bag (100 Pcs)", 1, "", "/categories/bijili-crackers.jpg", 30],
  ["MYL-BJL-02", "Stripped Bijili 100", 225, "1 Bag (100 Pcs)", 1, "", "/categories/bijili-crackers.jpg", 45],
  ["MYL-SD-01", "28 Chorsa", 125, "1 pocket", 1, "", "/categories/sound-crackers.jpg", 25],
  ["MYL-SD-02", "56 Giant", 500, "1 pocket", 1, "", "/categories/sound-crackers.jpg", 100],
  ["MYL-SD-03", "100 watts", 150, "1 BOX", 1, "", "/categories/sound-crackers.jpg", 30],
  ["MYL-SD-04", "200 Watts", 325, "1 BOX", 1, "", "/categories/sound-crackers.jpg", 65],
  ["MYL-SD-05", "1k watts", 900, "1 BOX (10 PCS)", 1, "", "/categories/sound-crackers.jpg", 180],
  ["MYL-SD-06", "2k watts", 1800, "1 BOX (10 PCS)", 1, "", "/categories/sound-crackers.jpg", 360],
  ["MYL-SD-07", "5k watts", 4500, "1 BOX (10 PCS)", 1, "", "/categories/sound-crackers.jpg", 900],
  ["MYL-SD-08", "10k watts", 9000, "1 BOX (10 PCS)", 1, "", "/categories/sound-crackers.jpg", 1800],
  ["MYL-GCK-01", "Ground Chakkar Big 10Pcs", 195, "1 Box (10 Pcs)", 1, "", "/categories/ground-chakkar.jpg", 39],
  ["MYL-GCK-02", "Ground Chakkar Special", 340, "1 Box (10 Pcs)", 1, "", "/categories/ground-chakkar.jpg", 68],
  ["MYL-GCK-03", "Ground Chakkar Deluxe", 550, "1 Box (10 Pcs)", 1, "", "/categories/ground-chakkar.jpg", 110],
  ["MYL-GCK-04", "Spinner Deluxe", 850, "1 Box (5 Pcs)", 1, "", "/categories/ground-chakkar.jpg", 170],
  ["MYL-GCK-05", "Wire Chakkar", 1000, "1 BOX (10 PCS)", 1, "", "/categories/ground-chakkar.jpg", 200],
  ["MYL-TWN-01", "1 1/2' Twinkling Stars", 120, "1 Box (10 Pcs)", 1, "", "/categories/twinkling-star.jpg", 24],
  ["MYL-TWN-02", "4' Twinkling Stars", 325, "1 Box (10 Pcs)", 1, "", "/categories/twinkling-star.jpg", 65],
  ["MYL-FLP-01", "Flower Pots Big", 330, "1 Box (10 Pcs)", 1, "", "/products/flower-pots/dass-deluxe.jpg", 66],
  ["MYL-FLP-02", "Flower Pots Special", 440, "1 Box (10 Pcs)", 1, "", "/products/flower-pots/special.jpg", 88],
  ["MYL-FLP-03", "Flower Pots Asoka", 550, "1 Box (10 Pcs)", 1, "", "/products/flower-pots/asoka.jpg", 110],
  ["MYL-FLP-04", "Colour Kotti", 1000, "1 Box (10 Pcs)", 1, "", "/categories/flower-pots.jpg", 200],
  ["MYL-FLP-05", "Colour Kotti Deluxe", 1575, "1 Box (10 Pcs)", 1, "", "/products/flower-pots/giant.jpg", 315],
  ["MYL-RKT-01", "Rocket Bomb", 700, "1 Box (10 Pcs)", 1, "", "/categories/rockets.jpg", 140],
  ["MYL-RKT-02", "Musical Rocket", 1000, "1 Box (10 Pcs)", 1, "", "/categories/rockets.jpg", 200],
  ["MYL-PNC-01", "Hi tech pencil", 500, "1 BOX", 1, "", "/categories/candles.jpg", 100],
  ["MYL-PNC-02", "Nayagara Falls Handle", 820, "1 Box (5 Pcs)", 1, "", "/categories/candles.jpg", 164],
  ["MYL-BMB-01", "King Bomb", 550, "1 Box (10 Pcs)", 1, "", "/categories/bombs.jpg", 110],
  ["MYL-BMB-02", "Classic Bomb", 650, "1 Box (10 Pcs)", 1, "", "/categories/bombs.jpg", 130],
  ["MYL-BMB-03", "Jurassic Bomb Or Digital Bomb", 1050, "1 Box (10 Pcs)", 1, "", "/categories/bombs.jpg", 210],
  ["MYL-BMB-04", "Paper Bomb 1/4 Kg", 225, "1 Box", 1, "", "/categories/bombs.jpg", 45],
  ["MYL-BMB-05", "Paper Bomb 1/2 Kg", 450, "1 Box", 1, "", "/categories/bombs.jpg", 90],
  ["MYL-BMB-06", "Paper Bomb 1 Kg", 900, "1 Box", 1, "", "/categories/bombs.jpg", 180],
  ["MYL-FTN-01", "Tom and Jerry", 125, "1 Box (5 Pcs)", 1, "", "/categories/fountains.jpg", 25],
  ["MYL-FTN-02", "Tricolour Fountain", 1400, "1 Box (5 Pcs)", 1, "", "/products/fountains/tri-colors.png", 280],
  ["MYL-FTN-03", "Colour Rain", 650, "1 Box (5 Pcs)", 1, "", "/categories/fountains.jpg", 130],
  ["MYL-FTN-04", "Fox Star", 700, "1 Box", 1, "", "/products/fountains/jet-fountain.jpg", 140],
  ["MYL-FTN-05", "Sing Pop", 725, "1 Box", 1, "", "/categories/fountains.jpg", 145],
  ["MYL-FTN-06", "Mega Siren", 900, "1 Box (3 Pcs)", 1, "", "/categories/fountains.jpg", 180],
  ["MYL-FTN-07", "Mini Siren", 600, "1 Box (3 Pcs)", 1, "", "/categories/fountains.jpg", 120],
  ["MYL-FTN-08", "Peacock Feather", 850, "1 Box (2 Pcs)", 1, "", "/products/fountains/mori-barat-koti.jpg", 170],
  ["MYL-FTN-09", "H2O Falls", 750, "1 Box (1 Pc)", 1, "", "/categories/fountains.jpg", 150],
  ["MYL-FTN-10", "LION Fountain", 1250, "1 Box", 1, "", "/categories/fountains.jpg", 250],
  ["MYL-FTN-11", "Water Queen", 750, "1 Box (1 Pc)", 1, "", "/categories/fountains.jpg", 150],
  ["MYL-FTN-12", "Peacock Multicolour", 850, "1 Box (1 Pc)", 1, "", "/categories/fountains.jpg", 170],
  ["MYL-FTN-13", "Bada Peacock", 1700, "1 Box (1 Pc)", 1, "", "/categories/fountains.jpg", 340],
  ["MYL-FTN-14", "Colour Smoke", 650, "1 Box (3 Pcs)", 1, "", "/categories/fountains.jpg", 130],
  ["MYL-FTN-15", "4x4 Whistling Wheel", 1100, "1 Box (3 Pcs)", 1, "", "/categories/fountains.jpg", 220],
  ["MYL-FTN-16", "Lotus Wheel", 575, "1 Box (3 Pcs)", 1, "", "/categories/fountains.jpg", 115],
  ["MYL-FTN-17", "Tin", 600, "1 Box (1 Pc)", 1, "", "/categories/fountains.jpg", 120],
  ["MYL-KDS-01", "Elephant Fountain", 1150, "1 Box", 1, "", "/categories/kids-special.jpg", 230],
  ["MYL-KDS-02", "Race Car", 1250, "1 Box (2 Pcs)", 1, "", "/categories/kids-special.jpg", 250],
  ["MYL-KDS-03", "GULFI", 1100, "1 BOX", 1, "", "/categories/kids-special.jpg", 220],
  ["MYL-KDS-04", "Murugar Vel special", 1100, "1 Box", 1, "", "/categories/kids-special.jpg", 220],
  ["MYL-KDS-05", "Drone", 775, "1 Box (5 Pcs)", 1, "", "/categories/kids-special.jpg", 155],
  ["MYL-KDS-06", "Helicopter", 500, "1 Box (5 Pcs)", 1, "", "/categories/kids-special.jpg", 100],
  ["MYL-KDS-07", "Free Fire Gun", 1750, "1 Box (2pc)", 1, "", "/categories/kids-special.jpg", 350],
  ["MYL-KDS-08", "Bambaram", 500, "1 Box (10 Pcs)", 1, "", "/categories/kids-special.jpg", 100],
  ["MYL-KDS-09", "Photo Flash", 300, "1 Box (5 Pcs)", 1, "", "/categories/kids-special.jpg", 60],
  ["MYL-KDS-10", "Insta Selfie", 675, "1 Box (5 Pcs)", 1, "", "/categories/kids-special.jpg", 135],
  ["MYL-KDS-11", "AK 47 GUN", 1000, "1 Box (5 Pcs)", 1, "", "/categories/kids-special.jpg", 200],
  ["MYL-KDS-12", "Bahubali Sword", 1000, "1 Box", 1, "", "/categories/kids-special.jpg", 200],
  ["MYL-SKY-01", "Chotta Fancy", 200, "1 Box (1 Pc)", 1, "", "/categories/sky-shots.jpg", 40],
  ["MYL-SKY-02", "2\" Fancy", 550, "1 Box (1 Pc)", 1, "", "/categories/sky-shots.jpg", 110],
  ["MYL-SKY-03", "2\" Fancy (3 Pc)", 1250, "1 Box (3 Pcs)", 1, "", "/categories/sky-shots.jpg", 250],
  ["MYL-SKY-04", "3.5\" Single Smash", 1600, "1 Box (1 Pc)", 1, "", "/categories/sky-shots.jpg", 320],
  ["MYL-SKY-05", "3.5\" Knight Series (2 Pc)", 2800, "1 Box (2 Pcs)", 1, "", "/categories/sky-shots.jpg", 560],
  ["MYL-SKY-06", "3.5\" Double Ball", 2100, "1 Box (1 Pc)", 1, "", "/categories/sky-shots.jpg", 420],
  ["MYL-SKY-07", "4\" Glory Series", 2300, "1 Box (1 Pc)", 1, "", "/categories/sky-shots.jpg", 460],
  ["MYL-SKY-08", "4\"Twins (2pc)", 3950, "1 Box (2Pc)", 1, "", "/categories/sky-shots.jpg", 790],
  ["MYL-SKY-09", "4\" Nayagara Falls Gold", 1900, "1 Box (1 Pc)", 1, "", "/categories/sky-shots.jpg", 380],
  ["MYL-SKY-10", "4\" Nayagara Falls Crackling", 1900, "1 Box (1 Pc)", 1, "", "/categories/sky-shots.jpg", 380],
  ["MYL-SKY-11", "Diwali Fabulous Celebration (12pipe)", 17500, "1 Box (1 Pc)", 1, "", "/categories/sky-shots.jpg", 3500],
  ["MYL-MLT-01", "15 Shots Colour", 1000, "1 Box (1 Pc)", 1, "", "/categories/multi-shots.jpg", 200],
  ["MYL-MLT-02", "30 Shots Colour", 2000, "1 Box (1 Pc)", 1, "", "/categories/multi-shots.jpg", 400],
  ["MYL-MLT-03", "60 Shots Colour", 4000, "1 Box (1 Pc)", 1, "", "/categories/multi-shots.jpg", 800],
  ["MYL-MLT-04", "120 Shots Colour", 8000, "1 Box (1 Pc)", 1, "", "/categories/multi-shots.jpg", 1600],
  ["MYL-MLT-05", "240 Shots Colour", 16000, "1 Box (1 Pc)", 1, "", "/categories/multi-shots.jpg", 3200],
  ["MYL-PF-01", "HAND SHOT New", 3000, "1 BOX (10 PCS)", 1, "", "/categories/premium-fountains.jpg", 600],
  ["MYL-SPK-01", "7cm Electric Sparklers", 50, "1 Box (10 Pcs)", 1, "", "/categories/sparklers.jpg", 10],
  ["MYL-SPK-02", "7cm Colour Sparklers", 60, "1 Box (10 Pcs)", 1, "", "/categories/sparklers.jpg", 12],
  ["MYL-SPK-03", "7cm Green Sparklers", 70, "1 Box (10 Pcs)", 1, "", "/categories/sparklers.jpg", 14],
  ["MYL-SPK-04", "7cm Red Sparklers", 85, "1 Box (10 Pcs)", 1, "", "/categories/sparklers.jpg", 17],
  ["MYL-SPK-05", "10cm Electric Sparklers", 90, "1 Box (10 Pcs)", 1, "", "/categories/sparklers.jpg", 18],
  ["MYL-SPK-06", "10cm Colour Sparklers", 100, "1 Box (10 Pcs)", 1, "", "/categories/sparklers.jpg", 20],
  ["MYL-SPK-07", "10cm Green Sparklers", 115, "1 Box (10 Pcs)", 1, "", "/categories/sparklers.jpg", 23],
  ["MYL-SPK-08", "10cm Red Sparklers", 135, "1 Box (10 Pcs)", 1, "", "/categories/sparklers.jpg", 27],
  ["MYL-SPK-09", "12cm Electric Sparklers", 140, "1 Box (10 Pcs)", 1, "", "/categories/sparklers.jpg", 28],
  ["MYL-SPK-10", "12cm Colour Sparklers", 160, "1 Box (10 Pcs)", 1, "", "/categories/sparklers.jpg", 32],
  ["MYL-SPK-11", "12cm Green Sparklers", 180, "1 Box (10 Pcs)", 1, "", "/categories/sparklers.jpg", 36],
  ["MYL-SPK-12", "12cm Red Sparklers", 200, "1 Box (10 Pcs)", 1, "", "/categories/sparklers.jpg", 40],
  ["MYL-SPK-13", "15cm Electric Sparklers", 190, "1 Box (10 Pcs)", 1, "", "/categories/sparklers.jpg", 38],
  ["MYL-SPK-14", "15cm Colour Sparklers", 210, "1 Box (10 Pcs)", 1, "", "/categories/sparklers.jpg", 42],
  ["MYL-SPK-15", "15cm Green Sparklers", 230, "1 Box (10 Pcs)", 1, "", "/categories/sparklers.jpg", 46],
  ["MYL-SPK-16", "15cm Red Sparklers", 260, "1 Box (10 Pcs)", 1, "", "/categories/sparklers.jpg", 52],
  ["MYL-SPK-17", "30cm Electric Sparklers", 230, "1 Box (5 Pcs)", 1, "", "/categories/sparklers.jpg", 46],
  ["MYL-SPK-18", "30cm Colour Sparklers", 250, "1 Box (5 Pcs)", 1, "", "/categories/sparklers.jpg", 50],
  ["MYL-SPK-19", "30cm Green Sparklers", 270, "1 Box (5 Pcs)", 1, "", "/categories/sparklers.jpg", 54],
  ["MYL-SPK-20", "30cm Red Sparklers", 290, "1 Box (5 Pcs)", 1, "", "/categories/sparklers.jpg", 58],
  ["MYL-SPK-21", "50cm Electric Sparklers", 750, "1 Box (5 Pcs)", 1, "", "/categories/sparklers.jpg", 150],
  ["MYL-SPK-22", "50cm Colour Sparklers", 850, "1 Box (5 Pcs)", 1, "", "/categories/sparklers.jpg", 170],
  ["MYL-SPK-23", "50cm Red Sparklers", 1350, "1 Box (5 Pcs)", 1, "", "/categories/sparklers.jpg", 270],
  ["MYL-SPK-24", "50cm Green Sparklers", 1150, "1 Box (5 Pcs)", 1, "", "/categories/sparklers.jpg", 230],
  ["MYL-SPK-25", "Rotating Sparklers", 250, "1 Box", 1, "", "/categories/sparklers.jpg", 50],
  ["MYL-NVL-01", "ROLL CAPS", 300, "1 BOX (10 PCS)", 1, "", "/categories/novelties.jpg", 60],
  ["MYL-NVL-02", "BLACK SERPENTS", 150, "1 Box", 1, "", "/categories/novelties.jpg", 30],
  ["MYL-NVL-03", "SUPER MATCHES", 400, "1 Box (5 Pcs)", 1, "", "/categories/novelties.jpg", 80],
  ["MYL-NVL-04", "LAPTOP MEGA 10 in 1 MATCHES", 850, "1 Box (10 Pcs)", 1, "", "/categories/novelties.jpg", 170],
  ["MYL-GFT-01", "30 Items (5pc Packs)", 2000, "1 Box", 1, "", "/categories/gift-boxes.jpg", 400],
  ["MYL-GFT-02", "40 Items (5pc Packs)", 3000, "1 Box", 1, "", "/categories/gift-boxes.jpg", 600],
  ["MYL-GFT-03", "50 items (5pc pack)", 4000, "1 box", 1, "", "/categories/gift-boxes.jpg", 800],
  ["MYL-GFT-04", "25 items (10pc Pack)", 1875, "1 Box", 1, "", "/categories/gift-boxes.jpg", 375],
  ["MYL-GFT-05", "30 items (10pc Pack)", 2200, "1 BOX (10 PCS)", 1, "", "/categories/gift-boxes.jpg", 440],
  ["MYL-GFT-06", "35items(10pc Pack)", 2700, "1 BOX", 1, "", "/categories/gift-boxes.jpg", 540],
  ["MYL-GFT-07", "42 items(10pc Pack)", 3000, "1 BOX", 1, "", "/categories/gift-boxes.jpg", 600],
  ["MYL-GFT-08", "50 items (10pc Pack)", 4000, "1 BOX", 1, "", "/categories/gift-boxes.jpg", 800],
];
